\i database/migrations/0001_users.up.sql
\i database/migrations/0002_schools.up.sql
\i database/migrations/0003_timetables.up.sql
\i database/migrations/0004_lessons.up.sql
\i database/migrations/0005_payments.up.sql
\i database/migrations/0006_messages.up.sql
\i database/migrations/0007_reports.up.sql
\i database/migrations/0008_alter_for_old.up.sql
\i database/migrations/0008_alter_messages_col_session.up.sql
\i database/migrations/0009_alter_school_settings_add_updated_at.sql
\i database/migrations/0010_alter_subject_exams_start_time.sql
\i database/migrations/0011_alter_period_grades_unique.sql
\i database/migrations/0012_alter_messages_reads_add_notified_at.sql
\i database/migrations/0013_alter_lessons_topics_add_book_id_book_page.sql
\i database/migrations/0014_alter_messages_parent_id.sql
\i database/migrations/0015_alter_schools_add_galleries_latitude_longlitude.sql
\i database/migrations/0016_alter_users_add_new_fields.sql
\i database/migrations/0017_alter_subjects_add_period_id_base_subject_id_fields.sql
\i database/migrations/0018_alter_base_subjects_add_school_id_is_available.sql
\i database/migrations/0019_alter_period_grade_unique.sql
\i database/migrations/0021_alter_payment_transaction_new_fields.sql
\i database/migrations/0022_settings.up.sql
\i database/migrations/0023_alter_classroom_add_period.sql
\i database/migrations/0024_alter_reports_and_report_items_table_add_new.sql
\i database/migrations/0025_teacher_excuses.up.sql
\i database/migrations/0026_contact_items_add_columns.up.sql
\i database/migrations/0028_alter_users_add_documents_field.sql
\i database/migrations/0029_user_payments.up.sql
\i database/migrations/0030_alter_table_periods_add_data_counts.sql
\i database/migrations/0031_alter_period_grades.sql
\i database/migrations/0032_alter_user_parents_changes.sql
\i database/migrations/0034_school_transfers.sql
-- \i database/migrations/0027_new_alters.sql
-- \i database/migrations/indexes.sql
